/* eslint-disable import/no-unresolved */
import { daFetch } from 'da-fetch';
import { crawl } from 'https://da.live/nx/public/utils/tree.js';
import { getSourceWithMeta, getSheets, saveSheets } from './da-utils.js';
import { ORG, REPO, getAdminPreviewUrl, getHelixResourceStatusUrl, getScanRoots } from './paths-config.js';

export const LOG_PATH = '/tools/page-builder/landing-page/data/lpb-log';
export const SCAN_ROOT = '/resources';
export const MARKER_SELECTOR = '.table.hide-block.page-builder';
export const MARKER_NAME = 'landing-page-builder';

const REPO_PREFIX = `/${ORG}/${REPO}`;

function toRepoRelative(path) {
  if (!path) return path;
  return path.startsWith(REPO_PREFIX) ? path.slice(REPO_PREFIX.length) : path;
}

function stripHtmlExt(path) {
  return path?.replace(/\.html$/, '') ?? path;
}

function parseBlockRows(rowEls, cellSelector) {
  const data = {};
  rowEls.forEach((row) => {
    const cells = row.querySelectorAll(cellSelector);
    if (cells.length < 2) return;
    const key = cells[0].textContent?.trim();
    const value = cells[1].textContent?.trim();
    if (key) data[key] = value;
  });
  return data;
}

export function extractMarker(doc) {
  if (!doc?.querySelector) return null;

  // Format 1: Franklin-processed HTML — div with CSS classes (generated by addHiddenTable)
  const el = doc.querySelector(MARKER_SELECTOR);
  if (el) {
    const data = parseBlockRows([...el.querySelectorAll(':scope > div')], ':scope > div');
    if (data.name === MARKER_NAME) return data;
  }

  // Format 2: DA authoring table — block name is text in first cell, not a CSS class
  for (const table of doc.querySelectorAll('table')) {
    const rows = [...table.querySelectorAll('tr')];
    const headerText = rows[0]?.querySelector('td, th')?.textContent?.trim().toLowerCase() ?? '';
    if (rows.length >= 2 && headerText.includes('page-builder')) {
      const data = parseBlockRows(rows.slice(1), 'td, th');
      if (data.name === MARKER_NAME) return data;
    }
  }

  return null;
}

/**
 * Derive a content type from a page path, e.g. /resources/guides/foo -> guide.
 * Returns null if the path doesn't match a known bucket.
 */
export function deriveContentType(path) {
  if (!path) return null;
  const match = path.match(/\/resources\/([^/]+)\//);
  if (!match) return null;
  const bucket = match[1].toLowerCase();
  const map = {
    guides: 'guide',
    reports: 'report',
    videos: 'video/demo',
    infographics: 'infographic',
    sdk: 'ungated',
  };
  return map[bucket] ?? bucket;
}

/** Base64url-decode a JWT payload segment (padding is required for atob). */
export function decodeJwtPayloadSegment(segment) {
  if (!segment || typeof segment !== 'string') return null;
  const base64 = segment.replace(/-/g, '+').replace(/_/g, '/');
  const pad = (4 - (base64.length % 4)) % 4;
  const padded = base64 + '='.repeat(pad);
  try {
    return JSON.parse(atob(padded));
  } catch {
    return null;
  }
}

function imsPublisherFromPayload(payload) {
  if (!payload || typeof payload !== 'object') return null;
  if (payload.email) return String(payload.email);
  if (payload.preferred_username) return String(payload.preferred_username);
  if (payload.name && String(payload.name).trim()) return String(payload.name).trim();
  if (payload.user_id) return String(payload.user_id);
  if (payload.sub) return String(payload.sub);
  for (const key of Object.keys(payload)) {
    if (key.includes('adobelogin.com') || key.includes('adobe.com')) {
      const v = payload[key];
      if (typeof v === 'string' && v.includes('@')) return v;
      if (v && typeof v === 'object') {
        const inner = v.email || v.username || v.name || v.userId || v.user_id;
        if (inner) return String(inner);
      }
    }
  }
  return null;
}

/**
 * Decode an Adobe IMS access token JWT and return a best-effort publisher id.
 * Falls back to 'unknown' if the token is opaque or cannot be decoded.
 */
export function publisherFromToken(token) {
  if (!token || typeof token !== 'string') return 'unknown';
  const parts = token.split('.');
  if (parts.length < 2) return 'unknown';
  const payload = decodeJwtPayloadSegment(parts[1]);
  return imsPublisherFromPayload(payload) || 'unknown';
}

/**
 * From initIms() / loadIms(): getProfile() merged with accessToken (see da.live ims.js).
 */
export function publisherFromImsDetails(ims) {
  if (!ims || ims.anonymous === true) return null;
  if (typeof ims.email === 'string' && ims.email.trim()) return ims.email.trim();
  if (typeof ims.displayName === 'string' && ims.displayName.trim()) return ims.displayName.trim();
  if (ims.name) {
    if (typeof ims.name === 'string' && ims.name.trim()) return ims.name.trim();
    if (typeof ims.name === 'object') {
      const fn = ims.name.first_name || ims.name.first;
      const ln = ims.name.last_name || ims.name.last;
      const full = ims.name.full_name || ims.name.fullName;
      if (full) return String(full).trim();
      if (fn || ln) return [fn, ln].filter(Boolean).join(' ').trim() || null;
    }
  }
  const fn = ims.first_name || ims.firstName;
  const ln = ims.last_name || ims.lastName;
  if (fn || ln) return [fn, ln].filter(Boolean).join(' ').trim() || null;
  if (ims.userId) return String(ims.userId);
  if (ims.user_id) return String(ims.user_id);
  if (ims.username) return String(ims.username);
  if (ims.sub) return String(ims.sub);
  return null;
}

/**
 * Resolve publisher for the log row.
 * @param {object} sdkOrContext - DA SDK `{ context, token }` or plain `context` (tests / legacy).
 * @param {string} [imsAccessToken] - IMS bearer from initIms (used when sdk.token is absent).
 * @param {object} [imsDetails] - Full return value of initIms() (getProfile + accessToken).
 */
export function resolvePublisher(sdkOrContext, imsAccessToken, imsDetails) {
  const fromImsProfile = publisherFromImsDetails(imsDetails);
  if (fromImsProfile) return fromImsProfile;

  const ctx = sdkOrContext?.context ?? sdkOrContext;
  const bearer = imsAccessToken ?? sdkOrContext?.token;
  const u = ctx?.user ?? sdkOrContext?.user;

  if (typeof u === 'string' && u.trim()) return u.trim();
  if (u && typeof u === 'object') {
    const direct = u.email || u.mail || u.username
      || u.preferredUsername || u.preferred_username
      || u.displayName || u.name || u.givenName || u.given_name
      || u.userId || u.user_id || u.id || u.sub;
    if (direct) return String(direct);
  }
  if (ctx?.email) return String(ctx.email);
  if (ctx?.userEmail) return String(ctx.userEmail);
  if (ctx?.userName) return String(ctx.userName);

  return publisherFromToken(bearer);
}

async function fetchPublishState(repoRelativePath) {
  try {
    const htmlPath = `${String(repoRelativePath || '').replace(/\.html$/, '')}.html`;
    const res = await daFetch(getHelixResourceStatusUrl(htmlPath));
    if (!res.ok) return 'unpublished';
    const json = await res.json();
    return json.live?.lastModified ? 'published' : 'unpublished';
  } catch {
    return 'unpublished';
  }
}

async function readLog() {
  const sheet = await getSheets(LOG_PATH).catch(() => null);
  return Array.isArray(sheet?.data) ? sheet.data : [];
}

/**
 * Append or refresh a single row (called from LPB on publish).
 * Non-throwing: logs via lana on failure so publish flow is never blocked.
 */
export async function appendLogRow({ url, publisher, version, contentType } = {}) {
  if (!url) return null;
  const normalizedUrl = stripHtmlExt(url);
  const now = new Date().toISOString();
  try {
    const existing = await readLog();
    const index = existing.findIndex((row) => row.url === normalizedUrl);
    const prev = index >= 0 ? existing[index] : null;
    const row = {
      url: normalizedUrl,
      publishedAt: prev?.publishedAt || now,
      publishState: prev?.publishState || 'unpublished',
      publisher: publisher || prev?.publisher || 'unknown',
      version: version || prev?.version || '',
      contentType: contentType || prev?.contentType || deriveContentType(normalizedUrl) || '',
      lastSeenAt: now,
      status: 'active',
    };
    const next = index >= 0
      ? existing.map((r, i) => (i === index ? { ...r, ...row } : r))
      : [...existing, row];
    const res = await saveSheets(LOG_PATH, next);
    if (res?.ok) {
      try { await daFetch(getAdminPreviewUrl(`${LOG_PATH}.json`), { method: 'POST' }); } catch { /* preview best-effort */ }
    }
    return res;
  } catch (error) {
    window.lana?.log?.(`LPB log append failed: ${error?.message || error}`, { severity: 'warning', tags: 'landing-page-builder,lpb-log' });
    return null;
  }
}

/**
 * Walk SCAN_ROOT with DA's crawl utility, loading every HTML page and
 * extracting the LPB marker table when present.
 */
export async function scanResources({ onProgress, throttle = 10 } = {}) {
  const roots = getScanRoots();
  const rootsTotal = roots.length;
  let rootsDone = 0;
  const htmlPaths = [];

  // Synchronous callback — crawl utilities do not await async callbacks,
  // so async I/O here would complete after results resolves and be lost.
  const callback = (item) => {
    if (item.ext === 'html') htmlPaths.push(item.path);
  };

  await Promise.all(
    roots.map((root) => {
      const { results } = crawl({ path: `${REPO_PREFIX}${root}`, callback, throttle });
      return results.then(() => {
        rootsDone += 1;
        onProgress?.({ rootsDone, rootsTotal, pagesFound: htmlPaths.length });
      });
    }),
  );

  const found = [];
  // Process in throttle-sized chunks — avoids overwhelming the DA source API
  for (let i = 0; i < htmlPaths.length; i += throttle) {
    const chunk = htmlPaths.slice(i, i + throttle);
    // eslint-disable-next-line no-await-in-loop
    await Promise.all(chunk.map(async (path) => {
      const relativePath = toRepoRelative(path);
      const { doc, lastModifiedBy } = await getSourceWithMeta(relativePath).catch(() => (
        { doc: null, lastModifiedBy: null }
      ));
      const marker = extractMarker(doc);
      if (marker) {
        const fromMarker = (marker.publishedBy || marker.publisher || '').trim();
        const fromDa = (lastModifiedBy || '').trim();
        found.push({
          url: stripHtmlExt(relativePath),
          version: marker.version ?? '',
          publisher: fromDa || fromMarker,
          contentType: deriveContentType(relativePath) || '',
        });
      } else {
        // eslint-disable-next-line no-console
        console.log('[lpb-scan] no marker:', relativePath, doc ? 'source ok' : 'source unavailable');
      }
    }));
  }
  return found;
}

/**
 * Full rebuild: scan the resources folder, reconcile with the current sheet,
 * soft-delete rows for pages that no longer carry the marker, and persist.
 */
export async function rebuildLog({ onProgress, throttle = 10 } = {}) {
  const [found, existing] = await Promise.all([
    scanResources({ onProgress, throttle }),
    readLog(),
  ]);
  const now = new Date().toISOString();
  const byUrl = new Map(existing.map((row) => [row.url, row]));
  const foundUrls = new Set(found.map((row) => row.url));

  const publishStates = await Promise.all(found.map((row) => fetchPublishState(row.url)));

  const active = found.map((row, i) => {
    const prev = byUrl.get(row.url);
    const publisherOnDoc = row.publisher?.trim();
    return {
      url: row.url,
      publishedAt: prev?.publishedAt || now,
      publishState: publishStates[i],
      publisher: publisherOnDoc || prev?.publisher || 'unknown',
      version: row.version || prev?.version || '',
      contentType: row.contentType || prev?.contentType || '',
      lastSeenAt: now,
      status: 'active',
    };
  });

  const removed = existing
    .filter((row) => !foundUrls.has(row.url))
    .map((row) => ({
      ...row,
      status: 'removed',
      removedAt: row.removedAt || now,
    }));

  const next = [...active, ...removed];
  let res;
  try {
    res = await saveSheets(LOG_PATH, next);
  } catch (error) {
    const msg = error?.message || String(error);
    window.lana?.log?.(`LPB log rebuild save failed: ${msg}`, { severity: 'warning', tags: 'landing-page-builder,lpb-log' });
    return {
      rows: next,
      active: active.length,
      removed: removed.length,
      saved: false,
      saveError: msg,
    };
  }
  if (!res?.ok) {
    let saveError = `HTTP ${res.status || 'unknown'}`;
    try {
      const body = await res.text();
      if (body) saveError = `${saveError} — ${body.slice(0, 400)}`;
    } catch {
      /* ignore */
    }
    window.lana?.log?.(`LPB log rebuild save not ok: ${saveError}`, { severity: 'warning', tags: 'landing-page-builder,lpb-log' });
    return {
      rows: next,
      active: active.length,
      removed: removed.length,
      saved: false,
      saveError,
    };
  }
  try { await daFetch(getAdminPreviewUrl(`${LOG_PATH}.json`), { method: 'POST' }); } catch { /* preview best-effort */ }
  return { rows: next, active: active.length, removed: removed.length, saved: true };
}

export async function getLog() {
  return readLog();
}
